version: "3"

services:
  app:
    build: .
    command: yarn serve
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 8080:8080
    container_name: vue-app
    volumes:
      - .:/home/node/app
    networks:
      - server-network
    restart: unless-stopped
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3
    container_name: server-mongo-vue
    networks:
      - server-network
    ports:
      - 27017:27017
    build: ./.docker/mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
networks:
  server-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.58.1/24
